# Project: Taxi Ride Data Analysis from Peru

### In this project, I analyzed taxi ride data from Peru, using three datasets: passengers (passenger-side data), drivers (driver-side data), and taxi_2 (combined data for other trips). Each row corresponds to a single taxi ride.

In [21]:
import pandas as pd

In [22]:
passengers = pd.read_csv('passengers.csv')
drivers = pd.read_csv('drivers.csv')

In [23]:
print(f"Shape of passengers: {passengers.shape}")
print(f"Shape of drivers: {drivers.shape}")

Shape of passengers: (11555, 7)
Shape of drivers: (11555, 13)

In [24]:
passengers.head(7)

,journey_id,user_id,start_type,start_lat,start_lon,source,driver_score
0,23a1406fc6a11d866e3c82f22eed4d4c,0e9af5bbf1edfe591b54ecdfd7e91e26,asap,"-12,13983536","-77,02355957",iPhone,5.0
1,dd2af4715d0dc16eded53afc0e243577,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,13874817","-76,99536133",iPhone,NaN
2,dd91e131888064bf7df3ce08f3d4b4ad,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,12453079","-77,02780151",iPhone,NaN
3,dd2af4715d0dc16eded53afc0e2466d0,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,13885117","-76,99530029",iPhone,NaN
4,85b7eabcf5d84e42dc7629b7d27781af,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,08995438","-76,92626953",iPhone,4.0
5,2254715f0f569e3173ec61f16cbb8341,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,02241898","-77,10650635",iPhone,NaN
6,12432d83b49393bf25164673212b8295,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,08995819","-76,9262085",iPhone,5.0

In [25]:
drivers.head(7)

,journey_id,driver_id,taxi_id,icon,start_at,end_at,end_lat,end_lon,end_state,driver_start_lat,driver_start_lon,arrived_at,rider_score
0,23a1406fc6a11d866e3c82f22eed4d4c,583949a89a9ee17d19e3ca4f137b6b4c,b12f4f09c783e29fe0d0ea624530db56,executive,2010-11-16 16:44:00,2010-11-16 17:29:00,"-12,05537033","-77,0413208",drop off,"-12,10825481","-77,0272739",2010-11-16 17:02:00,5.0
1,dd2af4715d0dc16eded53afc0e243577,NaN,NaN,executive,2010-06-01 00:34:00,2010-06-01 00:37:00,"-12,12465668","-77,02886963",not found,NaN,NaN,NaN,NaN
2,dd91e131888064bf7df3ce08f3d4b4ad,NaN,NaN,executive,2010-05-31 05:01:00,2010-05-31 05:04:00,"-12,13883209","-76,99530029",not found,NaN,NaN,NaN,NaN
3,dd2af4715d0dc16eded53afc0e2466d0,NaN,NaN,executive,2010-06-01 00:29:00,2010-06-01 00:32:00,"-12,12458801","-77,02896118",not found,NaN,NaN,NaN,NaN
4,85b7eabcf5d84e42dc7629b7d27781af,d665fb9f75ef5d9cd0fd89479380ba78,0accdd3aa5a322f4129fa20b53278c69,executive,2010-09-11 23:55:00,2010-09-12 01:07:00,"-12,02223206","-77,10638428",drop off,"-12,08311558","-76,9277072",2010-09-11 23:50:00,5.0
5,2254715f0f569e3173ec61f16cbb8341,baacf396f773709519bbde35a5eab861,baacf396f773709519bbde35a585d91b,executive,2010-08-10 13:00:00,2010-08-10 14:26:00,"-12,08980179","-76,92608643",drop off,"-12,01706754","-77,05986526",2010-08-10 12:53:00,4.0
6,12432d83b49393bf25164673212b8295,e1332f68e81526e498e4d845233a6d7d,e1332f68e81526e498e4d845235baf80,executive,2010-08-08 12:10:00,2010-08-08 12:48:00,"-12,02152252","-77,10623169",drop off,"-12,08509125","-76,96944424",2010-08-08 12:01:00,5.0

In [26]:
taxi_1 = passengers.merge(drivers, on='journey_id')

taxi_1.head(7)

,journey_id,user_id,start_type,start_lat,start_lon,source,driver_score,driver_id,taxi_id,icon,start_at,end_at,end_lat,end_lon,end_state,driver_start_lat,driver_start_lon,arrived_at,rider_score
0,23a1406fc6a11d866e3c82f22eed4d4c,0e9af5bbf1edfe591b54ecdfd7e91e26,asap,"-12,13983536","-77,02355957",iPhone,5.0,583949a89a9ee17d19e3ca4f137b6b4c,b12f4f09c783e29fe0d0ea624530db56,executive,2010-11-16 16:44:00,2010-11-16 17:29:00,"-12,05537033","-77,0413208",drop off,"-12,10825481","-77,0272739",2010-11-16 17:02:00,5.0
1,dd2af4715d0dc16eded53afc0e243577,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,13874817","-76,99536133",iPhone,NaN,NaN,NaN,executive,2010-06-01 00:34:00,2010-06-01 00:37:00,"-12,12465668","-77,02886963",not found,NaN,NaN,NaN,NaN
2,dd91e131888064bf7df3ce08f3d4b4ad,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,12453079","-77,02780151",iPhone,NaN,NaN,NaN,executive,2010-05-31 05:01:00,2010-05-31 05:04:00,"-12,13883209","-76,99530029",not found,NaN,NaN,NaN,NaN
3,dd2af4715d0dc16eded53afc0e2466d0,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,13885117","-76,99530029",iPhone,NaN,NaN,NaN,executive,2010-06-01 00:29:00,2010-06-01 00:32:00,"-12,12458801","-77,02896118",not found,NaN,NaN,NaN,NaN
4,85b7eabcf5d84e42dc7629b7d27781af,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,08995438","-76,92626953",iPhone,4.0,d665fb9f75ef5d9cd0fd89479380ba78,0accdd3aa5a322f4129fa20b53278c69,executive,2010-09-11 23:55:00,2010-09-12 01:07:00,"-12,02223206","-77,10638428",drop off,"-12,08311558","-76,9277072",2010-09-11 23:50:00,5.0
5,2254715f0f569e3173ec61f16cbb8341,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,02241898","-77,10650635",iPhone,NaN,baacf396f773709519bbde35a5eab861,baacf396f773709519bbde35a585d91b,executive,2010-08-10 13:00:00,2010-08-10 14:26:00,"-12,08980179","-76,92608643",drop off,"-12,01706754","-77,05986526",2010-08-10 12:53:00,4.0
6,12432d83b49393bf25164673212b8295,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,08995819","-76,9262085",iPhone,5.0,e1332f68e81526e498e4d845233a6d7d,e1332f68e81526e498e4d845235baf80,executive,2010-08-08 12:10:00,2010-08-08 12:48:00,"-12,02152252","-77,10623169",drop off,"-12,08509125","-76,96944424",2010-08-08 12:01:00,5.0

In [27]:
taxi_1.shape

(11555, 19)

In [28]:
taxi_1.dtypes

journey_id           object
user_id              object
start_type           object
start_lat            object
start_lon            object
source               object
driver_score        float64
driver_id            object
taxi_id              object
icon                 object
start_at             object
end_at               object
end_lat              object
end_lon              object
end_state            object
driver_start_lat     object
driver_start_lon     object
arrived_at           object
rider_score         float64
dtype: object

In [29]:
taxi_2 = pd.read_csv('taxi_2.csv')
taxi_2.head(7)

,journey_id,user_id,driver_id,taxi_id,icon,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,driver_start_lat,driver_start_lon,arrived_at,source,driver_score,rider_score
0,b6206048fbda6d454ead4fa2b4b9beaf,d0de230345480ca6bcc86ce1eb89fbfa,40187316352d2c03ddc19e9c8ad7c514,42aa958edf790ef3d45823386fb734ea,executive,asap,2010-11-30 03:38:00,"-11,95227432","-76,81442261",2010-11-30 03:39:00,"40,4052887","-3,72117424",rider cancel,"-12,08863069","-76,96650439",NaN,iPhone,NaN,NaN
1,d2cf43d9f47c6512b84e1ea7b8746a0c,8e37a68fab5f31a5e2c1b5f77c6bb9e5,1d8ba0bdacccf2d0d70ee9925185d231,1d8ba0bdacccf2d0d70ee99251862c54,executive,reserved,2010-11-28 22:30:00,"-12,0495456","-77,1116799",2010-11-29 00:22:00,"-12,11973","-76,998734",drop off,"-12,04809647","-77,096405",2010-11-28 22:02:00,web,NaN,NaN
2,7c01cd25b39f4f8b234bf56d48a5e9c9,8e37a68fab5f31a5e2c1b5f77c6bb9e5,ecdcce0c956e266ed26c80fd9e5cbb8f,1d3c551d7fc3d0daf73f0a8c82781c2d,executive,reserved,2010-11-28 22:30:00,"-12,0511575","-77,1300437",2010-11-28 23:04:00,"-12,0794453","-77,0896372",drop off,0,0,2010-11-28 22:34:00,web,NaN,NaN
3,ab90a1bf4289d96e78d4a47d7cc2286d,1e639fc120efea2675ac138ebeac4c2f,12c472dd8efc6ed622ae8669251b82f1,c26f22be31323781fd478dbcf8926d44,executive,asap,2010-11-28 01:04:00,"-12,0979889","-77,0223812",2010-11-28 01:32:00,"-12,1192177","-77,0413569",drop off,"-12,08757569","-77,03611258",2010-11-28 01:15:00,web,NaN,4.0
4,d2cf43d9f47c6512b84e1ea7b8740874,2f1882c87731970df63e69d4bc254f96,3abce16ea601affbeae8f50584ce72ef,ab6ee368af1a9e1293acc0d14d1f9338,executive,reserved,2010-11-28 01:50:00,"-12,0903136","-77,0424105",2010-11-28 02:18:00,"43,5398067","-5,6575304",drop off,"-12,11418993","-77,03732522",2010-11-28 01:43:00,Wap,NaN,5.0
5,fac8de6201087465a99a7b82a9e6964e,fa88b809b28e4387f72703c52ae49bb7,b66c43e298753a3d39220e53008a4325,b66c43e298753a3d39220e53008a4f19,executive,asap,2010-11-28 01:43:00,"-12,12494659","-77,01104736",2010-11-28 02:13:00,"-12,11608887","-77,03796387",drop off,"-12,14234877","-76,99142485",2010-11-28 01:54:00,iPhone,NaN,5.0
6,d439fbb315b2966b8c84e219ecf82b65,9b22b91f3fa3f39566f27c1280225ed5,3bf29409837105b97d9548014095defd,f84c35d4d31654b733af0657b05f9b11,executive,asap,2010-12-01 00:36:00,"-12,10547606","-76,99768804",2010-12-01 02:06:00,"-12,09794296","-76,97605234",drop off,"-12,105584","-76,9977544",2010-12-01 01:02:00,Android,NaN,5.0

In [30]:
taxi_2.shape

(11556, 19)

In [32]:
taxi = pd.concat([taxi_1,taxi_2]).reset_index(drop=True)
taxi.head(7)

,journey_id,user_id,start_type,start_lat,start_lon,source,driver_score,driver_id,taxi_id,icon,start_at,end_at,end_lat,end_lon,end_state,driver_start_lat,driver_start_lon,arrived_at,rider_score
0,23a1406fc6a11d866e3c82f22eed4d4c,0e9af5bbf1edfe591b54ecdfd7e91e26,asap,"-12,13983536","-77,02355957",iPhone,5.0,583949a89a9ee17d19e3ca4f137b6b4c,b12f4f09c783e29fe0d0ea624530db56,executive,2010-11-16 16:44:00,2010-11-16 17:29:00,"-12,05537033","-77,0413208",drop off,"-12,10825481","-77,0272739",2010-11-16 17:02:00,5.0
1,dd2af4715d0dc16eded53afc0e243577,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,13874817","-76,99536133",iPhone,NaN,NaN,NaN,executive,2010-06-01 00:34:00,2010-06-01 00:37:00,"-12,12465668","-77,02886963",not found,NaN,NaN,NaN,NaN
2,dd91e131888064bf7df3ce08f3d4b4ad,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,12453079","-77,02780151",iPhone,NaN,NaN,NaN,executive,2010-05-31 05:01:00,2010-05-31 05:04:00,"-12,13883209","-76,99530029",not found,NaN,NaN,NaN,NaN
3,dd2af4715d0dc16eded53afc0e2466d0,a553c46e3a22fb9c326aeb3d72b3334e,asap,"-12,13885117","-76,99530029",iPhone,NaN,NaN,NaN,executive,2010-06-01 00:29:00,2010-06-01 00:32:00,"-12,12458801","-77,02896118",not found,NaN,NaN,NaN,NaN
4,85b7eabcf5d84e42dc7629b7d27781af,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,08995438","-76,92626953",iPhone,4.0,d665fb9f75ef5d9cd0fd89479380ba78,0accdd3aa5a322f4129fa20b53278c69,executive,2010-09-11 23:55:00,2010-09-12 01:07:00,"-12,02223206","-77,10638428",drop off,"-12,08311558","-76,9277072",2010-09-11 23:50:00,5.0
5,2254715f0f569e3173ec61f16cbb8341,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,02241898","-77,10650635",iPhone,NaN,baacf396f773709519bbde35a5eab861,baacf396f773709519bbde35a585d91b,executive,2010-08-10 13:00:00,2010-08-10 14:26:00,"-12,08980179","-76,92608643",drop off,"-12,01706754","-77,05986526",2010-08-10 12:53:00,4.0
6,12432d83b49393bf25164673212b8295,56772d544fdfa589a020a1ff894a86f7,reserved,"-12,08995819","-76,9262085",iPhone,5.0,e1332f68e81526e498e4d845233a6d7d,e1332f68e81526e498e4d845235baf80,executive,2010-08-08 12:10:00,2010-08-08 12:48:00,"-12,02152252","-77,10623169",drop off,"-12,08509125","-76,96944424",2010-08-08 12:01:00,5.0

In [33]:
taxi.shape

(23111, 19)

In [35]:
taxi.isna().sum()

journey_id              0
user_id                 0
start_type              0
start_lat               0
start_lon               0
source                123
driver_score        15461
driver_id            3385
taxi_id              3385
icon                    0
start_at                0
end_at                276
end_lat                 0
end_lon                 0
end_state              12
driver_start_lat     3490
driver_start_lon     3490
arrived_at           5395
rider_score          7721
dtype: int64